include:
  - component: gitlab.com/to-be-continuous/docker/gitlab-ci-docker@5.10.2
    inputs:
      release-extra-tags: latest
      hadolint-args: -terror
      trivy-disabled: true
      sbom-disabled: true
      build-cache-disabled: true
    rules:
      - changes:
        - Dockerfile
        - src/**/*
        - package.json
      - if: $CI_PIPELINE_SOURCE == "web"
      - if: $CI_COMMIT_TAG

# Si no se cumplen las reglas de include:component, no se incluyen los jobs, haciendo que falle el pipeline
# https://gitlab.com/gitlab-org/gitlab/-/issues/341693
dummy:
  rules:
    - when: never
  script:
    - exit 0
