# NOTE: Este es un compose minimalista hecho para probar el backend, para el deploy completo mira:
# https://gitlab.com/cchadpip/cchad-deploy

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./sql/up.sql:/docker-entrypoint-initdb.d/up.sql
    networks:
      - bridge-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 15s
      timeout: 15s
      retries: 4

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      SMTP_SECURE: ${SMTP_SECURE}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - ${APP_PORT}:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
