services:
  db:
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./sql/up.sql:/docker-entrypoint-initdb.d/up.sql
    networks:
      - bridge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 15s
      retries: 4

  backend:
    build: ./
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      MAILDEV_INCOMING_USER: ${MAILDEV_INCOMING_USER}
      MAILDEV_INCOMING_PASS: ${MAILDEV_INCOMING_PASS}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
