services:
  db:
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./sql/up.sql:/docker-entrypoint-initdb.d/up.sql
    networks:
      - bridge-network
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 15s
      timeout: 15s
      retries: 4

  backend-dev:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      SMTP_SECURE: ${SMTP_SECURE}
      JWT_SECRET: ${JWT_SECRET}
      APP_PORT: ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    networks:
      - bridge-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
